### ISSUE TITLE
Create Reusable Build/Test Workflow and Add Release Workflow for PyPI/TestPyPI

### ISSUE THREAD

**Issue by reayd-falmouth** [reayd-falmouth/gnubg-nn-pypi#16]
**Description:**

Refactor GitHub Actions to improve reuse and separation of concerns:

---

#### 1. Create reusable workflow: `.github/workflows/build_and_test.yml`

This workflow will:

* Check out the code
* Set up Python
* Install `build`, `pytest`
* Build the Python package
* Run the test suite

```yaml
name: Reusable Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          pip install -U pip build pytest

      - name: Build package
        run: python -m build

      - name: Run tests
        run: pytest
```

---

#### 2. Update `build_test.yml` to use the reusable workflow

```yaml
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml
```

---

#### 3. Create `release.yml` to trigger PyPI/TestPyPI uploads

```yaml
name: Release to PyPI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Release environment (test or prod)"
        required: true
        default: "test"

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      PYPI_REPOSITORY_URL: ${{ github.event.inputs.environment == 'prod' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install twine
        run: pip install twine

      - name: Publish to PyPI/TestPyPI
        run: twine upload --repository-url ${{ env.PYPI_REPOSITORY_URL }} dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
```

---

### 🔐 Required Secrets

* `PYPI_USERNAME`
* `PYPI_PASSWORD`
